import * as organisation from './organisation';
import * as pubkey from './pubkey';
import * as curation from './curation';
import * as data from './data';
import * as files from './files';
import * as log from './log';
import * as permission from './permission';
import * as study from './study';
import * as user from './user';
import * as config from './config';
import * as doc from './doc';
import * as webauthn from './webauthn';
export * from './organisation';
export * from './pubkey';
export * from './curation';
export * from './data';
export * from './files';
export * from './log';
export * from './permission';
export * from './study';
export * from './user';
export * from './config';
export * from './doc';
export * from './webauthn';
export const GQLRequests = { ...organisation, ...pubkey, ...curation, ...data, ...files, ...log, ...permission, ...study, ...user, ...config, ...doc, ...webauthn};
